//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Licença
    {
        public int ID_TipoLicenca { get; set; }
        public string TipoLicenca { get; set; }
        public Nullable<int> Deleted { get; set; }
    }
}
