//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_GCA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_Maquina
    {
        public int ID_Maquina { get; set; }
        public string Maquina { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> Deleted { get; set; }
        public Nullable<int> ID_Setor { get; set; }
        public Nullable<int> ID_Chave { get; set; }
        public Nullable<int> ID_Usuario { get; set; }
    }
}
